[rewrite_local]
^https://api\.suyang123\.com/api/product/user/info/for/app url script-response-body https://raw.githubusercontent.com/1009394958/ywld-vip-unlock/main/ywld_user.js
^https://api\.suyang123\.com/api/product/yw/poem/summary url script-response-body https://raw.githubusercontent.com/1009394958/ywld-vip-unlock/main/ywld_poem.js
[mitm]
hostname = api.suyang123.com
