#!name=语文朗读宝 VIP 解锁
#!desc=破解VIP权限，永久有效
#!version=1.0

[rewrite_local]
^https:\/\/api\.suyang123\.com\/api\/product\/user\/info\/for\/app url script-response-body ywld_vip.js
^https:\/\/api\.suyang123\.com\/api\/product\/yw\/poem\/summary url script-response-body ywld_vip.js

[mitm]
hostname = api.suyang123.com


=================================================
  使用方法：
  1. 添加本链接为重写订阅
  2. 将 ywld_vip.js 添加为子资源 (资源配额 → 子资源 → 添加)
  3. 开启 MitM 并信任证书
=================================================